// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: ForegroundNotificationHandler.kt
// Package: com.lightningkite.butterfly.fcm
import Butterfly
import Foundation

public protocol ForegroundNotificationHandler: AnyObject {
    
    func handleNotificationInForeground(map: Dictionary<String, String>) -> ForegroundNotificationHandlerResult
}
public extension ForegroundNotificationHandler {
    func handleNotificationInForeground(map: Dictionary<String, String>) -> ForegroundNotificationHandlerResult {
        print("Received notification in foreground with \(map)")
        return ForegroundNotificationHandlerResult.SHOW_NOTIFICATION
    }
}

public enum ForegroundNotificationHandlerResult: String, KEnum, StringEnum, CaseIterable {
    case SUPPRESS_NOTIFICATION
    case SHOW_NOTIFICATION
    case UNHANDLED
    
    public init(from decoder: Decoder) throws {
        self = try Self(rawValue: decoder.singleValueContainer().decode(RawValue.self)) ?? .SUPPRESS_NOTIFICATION
    }
}



